### ISSUE TITLE
Publish the net.sharkfw:sharkfw-core artifact

### ISSUE THREAD

**Issue by yveskaufmann** [SharedKnowledge/SharkFW#8]
Our SharkNet API Build-Script is based on maven, which doesn't  allow it to easily inject jar files
manually. 

Im aware about the fact that we could already install the artifact locally with mvn install 
but this is error prone. 

A published net.sharkfw:sharkfw-core artifact would make our life easier.
I could provide support to create a bintray-repository and provide the  required code snippets
to publish the artifact to bintray based maven repository.

**Comment by j4rvis** [comment]
Perfect, thank you for your Offer to help us publish this repository. 
I accept the offer gratefully!

**Comment by yveskaufmann** [comment]
First step is to create bintray Account for the shark knowledge Organisation.
Can you create Bintray Account by login with your github Account by open http://bintray.com
after this i can add you to the Organisation

**Comment by j4rvis** [comment]
Okay perfect I created the account. Username is j4rvis.

**Comment by srmo** [comment]
I still don't see it on central's release repository, did this die?

**Comment by j4rvis** [comment]
Central release is not yet supported. Coming probably in the future. Currently best used using jitpack.io
